#### Import required libraries

In [1]:
import pandas as pd
import numpy as np

from sklearn.preprocessing import StandardScaler, MinMaxScaler, LabelEncoder, RobustScaler
import joblib

#### Load Dataset

In [34]:
df = pd.read_csv("../dataset/CICDDOS_Final_Dataset_B.csv", low_memory=False)

print("Dataset Loaded.")
print("Shape:", df.shape)

Dataset Loaded.
Shape: (346873, 79)

#### Inspect Dataset Structure

In [27]:
df.head(3)

,Protocol,Flow Duration,Total Fwd Packets,Total Backward Packets,Total Length of Fwd Packets,Total Length of Bwd Packets,Fwd Packet Length Max,Fwd Packet Length Min,Fwd Packet Length Mean,Fwd Packet Length Std,...,Active Mean,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min,Inbound,Label
0,17,1,2,0,1118.0,0.0,559.0,559.0,559.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1,MSSQL
1,17,1,2,0,458.0,0.0,229.0,229.0,229.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1,NetBIOS
2,17,2,2,0,2736.0,0.0,1368.0,1368.0,1368.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1,SNMP

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 461158 entries, 0 to 461157
Data columns (total 79 columns):
 #   Column                       Non-Null Count   Dtype
---  ------                       --------------   -----
 0   Protocol                     461158 non-null  int64
 1   Flow Duration                461158 non-null  int64
 2   Total Fwd Packets            461158 non-null  int64
 3   Total Backward Packets       461158 non-null  int64
 4   Total Length of Fwd Packets  461158 non-null  float64
 5   Total Length of Bwd Packets  461158 non-null  float64
 6   Fwd Packet Length Max        461158 non-null  float64
 7   Fwd Packet Length Min        461158 non-null  float64
 8   Fwd Packet Length Mean       461158 non-null  float64
 9   Fwd Packet Length Std        461158 non-null  float64
 10  Bwd Packet Length Max        461158 non-null  float64
 11  Bwd Packet Length Min        461158 non-null  float64
 12  Bwd Packet Length Mean       461158 non-null  float64
 13  Bwd Packet Length Std        461158 non-null  float64
 14  Flow Bytes/s                 458980 non-null  float64
 15  Flow Packets/s               461158 non-null  float64
 16  Flow IAT Mean                461158 non-null  float64
 17  Flow IAT Std                 461158 non-null  float64
 18  Flow IAT Max                 461158 non-null  float64
 19  Flow IAT Min                 461158 non-null  float64
 20  Fwd IAT Total                461158 non-null  float64
 21  Fwd IAT Mean                 461158 non-null  float64
 22  Fwd IAT Std                  461158 non-null  float64
 23  Fwd IAT Max                  461158 non-null  float64
 24  Fwd IAT Min                  461158 non-null  float64
 25  Bwd IAT Total                461158 non-null  float64
 26  Bwd IAT Mean                 461158 non-null  float64
 27  Bwd IAT Std                  461158 non-null  float64
 28  Bwd IAT Max                  461158 non-null  float64
 29  Bwd IAT Min                  461158 non-null  float64
 30  Fwd PSH Flags                461158 non-null  int64
 31  Bwd PSH Flags                461158 non-null  int64
 32  Fwd URG Flags                461158 non-null  int64
 33  Bwd URG Flags                461158 non-null  int64
 34  Fwd Header Length            461158 non-null  int64
 35  Bwd Header Length            461158 non-null  int64
 36  Fwd Packets/s                461158 non-null  float64
 37  Bwd Packets/s                461158 non-null  float64
 38  Min Packet Length            461158 non-null  float64
 39  Max Packet Length            461158 non-null  float64
 40  Packet Length Mean           461158 non-null  float64
 41  Packet Length Std            461158 non-null  float64
 42  Packet Length Variance       461158 non-null  float64
 43  FIN Flag Count               461158 non-null  int64
 44  SYN Flag Count               461158 non-null  int64
 45  RST Flag Count               461158 non-null  int64
 46  PSH Flag Count               461158 non-null  int64
 47  ACK Flag Count               461158 non-null  int64
 48  URG Flag Count               461158 non-null  int64
 49  CWE Flag Count               461158 non-null  int64
 50  ECE Flag Count               461158 non-null  int64
 51  Down/Up Ratio                461158 non-null  float64
 52  Average Packet Size          461158 non-null  float64
 53  Avg Fwd Segment Size         461158 non-null  float64
 54  Avg Bwd Segment Size         461158 non-null  float64
 55  Fwd Avg Bytes/Bulk           461158 non-null  int64
 56  Fwd Avg Packets/Bulk         461158 non-null  int64
 57  Fwd Avg Bulk Rate            461158 non-null  int64
 58  Bwd Avg Bytes/Bulk           461158 non-null  int64
 59  Bwd Avg Packets/Bulk         461158 non-null  int64
 60  Bwd Avg Bulk Rate            461158 non-null  int64
 61  Subflow Fwd Packets          461158 non-null  int64
 62  Subflow Fwd Bytes            461158 non-null  int64
 63  Subflow Bwd Packets          461158 non-null  int64
 64  Subflow Bwd Bytes            461158 non-null  int64
 65  Init_Win_bytes_forward       461158 non-null  int64
 66  Init_Win_bytes_backward      461158 non-null  int64
 67  act_data_pkt_fwd             461158 non-null  int64
 68  min_seg_size_forward         461158 non-null  int64
 69  Active Mean                  461158 non-null  float64
 70  Active Std                   461158 non-null  float64
 71  Active Max                   461158 non-null  float64
 72  Active Min                   461158 non-null  float64
 73  Idle Mean                    461158 non-null  float64
 74  Idle Std                     461158 non-null  float64
 75  Idle Max                     461158 non-null  float64
 76  Idle Min                     461158 non-null  float64
 77  Inbound                      461158 non-null  int64
 78  Label                        461158 non-null  object
dtypes: float64(45), int64(33), object(1)
memory usage: 278.0+ MB

In [28]:
df.describe()

d:\NewUser\Programs\miniconda3\Lib\site-packages\pandas\core\nanops.py:1016: RuntimeWarning: invalid value encountered in subtract
  sqr = _ensure_numeric((avg - values) ** 2)
d:\NewUser\Programs\miniconda3\Lib\site-packages\pandas\core\nanops.py:1016: RuntimeWarning: invalid value encountered in subtract
  sqr = _ensure_numeric((avg - values) ** 2)

,Protocol,Flow Duration,Total Fwd Packets,Total Backward Packets,Total Length of Fwd Packets,Total Length of Bwd Packets,Fwd Packet Length Max,Fwd Packet Length Min,Fwd Packet Length Mean,Fwd Packet Length Std,...,min_seg_size_forward,Active Mean,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min,Inbound
count,346873.000000,3.468730e+05,346873.000000,346873.000000,3.468730e+05,3.468730e+05,346873.000000,346873.000000,346873.000000,346873.000000,...,3.468730e+05,3.468730e+05,3.468730e+05,3.468730e+05,3.468730e+05,3.468730e+05,3.468730e+05,3.468730e+05,3.468730e+05,346873.000000
mean,15.924892,1.191548e+06,10.064274,0.756124,4.008724e+03,5.524603e+02,624.236755,598.735419,610.101883,9.179806,...,-3.718108e+07,7.941050e+03,2.692727e+03,1.150318e+04,6.266028e+03,4.049206e+05,3.202217e+04,4.320246e+05,3.791161e+05,0.925388
std,3.292063,9.023881e+06,367.948521,17.685275,3.359700e+04,3.673231e+04,524.833184,525.104802,517.979551,46.556791,...,1.952818e+08,1.750242e+05,7.840630e+04,2.338908e+05,1.625228e+05,3.870086e+06,6.354723e+05,4.071837e+06,3.748339e+06,0.262765
min,0.000000,0.000000e+00,1.000000,0.000000,0.000000e+00,0.000000e+00,0.000000,0.000000,0.000000,0.000000,...,-1.408238e+09,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000
25%,17.000000,1.000000e+00,2.000000,0.000000,4.580000e+02,0.000000e+00,229.000000,229.000000,229.000000,0.000000,...,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.000000
50%,17.000000,2.000000e+00,2.000000,0.000000,1.228000e+03,0.000000e+00,440.000000,401.000000,415.000000,0.000000,...,1.400000e+01,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.000000
75%,17.000000,1.106000e+03,4.000000,0.000000,2.944000e+03,0.000000e+00,1313.000000,1263.000000,1265.000000,0.000000,...,2.000000e+01,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.000000
max,17.000000,1.200000e+08,99538.000000,4632.000000,1.526642e+07,1.099376e+07,32120.000000,2114.000000,3015.290539,2221.556055,...,1.480000e+03,1.461992e+07,1.000007e+07,2.511954e+07,1.461992e+07,1.192194e+08,6.188006e+07,1.192194e+08,1.192194e+08,1.000000

In [29]:
df.columns

Index(['Protocol', 'Flow Duration', 'Total Fwd Packets',
       'Total Backward Packets', 'Total Length of Fwd Packets',
       'Total Length of Bwd Packets', 'Fwd Packet Length Max',
       'Fwd Packet Length Min', 'Fwd Packet Length Mean',
       'Fwd Packet Length Std', 'Bwd Packet Length Max',
       'Bwd Packet Length Min', 'Bwd Packet Length Mean',
       'Bwd Packet Length Std', 'Flow Bytes/s', 'Flow Packets/s',
       'Flow IAT Mean', 'Flow IAT Std', 'Flow IAT Max', 'Flow IAT Min',
       'Fwd IAT Total', 'Fwd IAT Mean', 'Fwd IAT Std', 'Fwd IAT Max',
       'Fwd IAT Min', 'Bwd IAT Total', 'Bwd IAT Mean', 'Bwd IAT Std',
       'Bwd IAT Max', 'Bwd IAT Min', 'Fwd PSH Flags', 'Bwd PSH Flags',
       'Fwd URG Flags', 'Bwd URG Flags', 'Fwd Header Length',
       'Bwd Header Length', 'Fwd Packets/s', 'Bwd Packets/s',
       'Min Packet Length', 'Max Packet Length', 'Packet Length Mean',
       'Packet Length Std', 'Packet Length Variance', 'FIN Flag Count',
       'SYN Flag Count', 'RST Flag Count', 'PSH Flag Count', 'ACK Flag Count',
       'URG Flag Count', 'CWE Flag Count', 'ECE Flag Count', 'Down/Up Ratio',
       'Average Packet Size', 'Avg Fwd Segment Size', 'Avg Bwd Segment Size',
       'Fwd Avg Bytes/Bulk', 'Fwd Avg Packets/Bulk', 'Fwd Avg Bulk Rate',
       'Bwd Avg Bytes/Bulk', 'Bwd Avg Packets/Bulk', 'Bwd Avg Bulk Rate',
       'Subflow Fwd Packets', 'Subflow Fwd Bytes', 'Subflow Bwd Packets',
       'Subflow Bwd Bytes', 'Init_Win_bytes_forward',
       'Init_Win_bytes_backward', 'act_data_pkt_fwd', 'min_seg_size_forward',
       'Active Mean', 'Active Std', 'Active Max', 'Active Min', 'Idle Mean',
       'Idle Std', 'Idle Max', 'Idle Min', 'Inbound', 'Label'],
      dtype='object')

In [4]:
df['Label'].unique()

array(['MSSQL', 'NetBIOS', 'SNMP', 'BENIGN', 'NTP', 'UDP', 'Portmap',
       'DNS', 'LDAP', 'UDPLag', 'SSDP', 'TFTP'], dtype=object)

### Data Cleaning

#### Clean Column Names

In [5]:
print("Train Column : ", df.columns)

Train Column :  Index(['Protocol', 'Flow Duration', 'Total Fwd Packets',
       'Total Backward Packets', 'Total Length of Fwd Packets',
       'Total Length of Bwd Packets', 'Fwd Packet Length Max',
       'Fwd Packet Length Min', 'Fwd Packet Length Mean',
       'Fwd Packet Length Std', 'Bwd Packet Length Max',
       'Bwd Packet Length Min', 'Bwd Packet Length Mean',
       'Bwd Packet Length Std', 'Flow Bytes/s', 'Flow Packets/s',
       'Flow IAT Mean', 'Flow IAT Std', 'Flow IAT Max', 'Flow IAT Min',
       'Fwd IAT Total', 'Fwd IAT Mean', 'Fwd IAT Std', 'Fwd IAT Max',
       'Fwd IAT Min', 'Bwd IAT Total', 'Bwd IAT Mean', 'Bwd IAT Std',
       'Bwd IAT Max', 'Bwd IAT Min', 'Fwd PSH Flags', 'Bwd PSH Flags',
       'Fwd URG Flags', 'Bwd URG Flags', 'Fwd Header Length',
       'Bwd Header Length', 'Fwd Packets/s', 'Bwd Packets/s',
       'Min Packet Length', 'Max Packet Length', 'Packet Length Mean',
       'Packet Length Std', 'Packet Length Variance', 'FIN Flag Count',
       'SYN Flag Count', 'RST Flag Count', 'PSH Flag Count', 'ACK Flag Count',
       'URG Flag Count', 'CWE Flag Count', 'ECE Flag Count', 'Down/Up Ratio',
       'Average Packet Size', 'Avg Fwd Segment Size', 'Avg Bwd Segment Size',
       'Fwd Avg Bytes/Bulk', 'Fwd Avg Packets/Bulk', 'Fwd Avg Bulk Rate',
       'Bwd Avg Bytes/Bulk', 'Bwd Avg Packets/Bulk', 'Bwd Avg Bulk Rate',
       'Subflow Fwd Packets', 'Subflow Fwd Bytes', 'Subflow Bwd Packets',
       'Subflow Bwd Bytes', 'Init_Win_bytes_forward',
       'Init_Win_bytes_backward', 'act_data_pkt_fwd', 'min_seg_size_forward',
       'Active Mean', 'Active Std', 'Active Max', 'Active Min', 'Idle Mean',
       'Idle Std', 'Idle Max', 'Idle Min', 'Inbound', 'Label'],
      dtype='object')

#### Drop unnecessary columns

In [35]:
df.drop(columns=['Unnamed: 0'], inplace=True, errors='ignore')

- fix the column name

In [36]:
df.columns = df.columns.str.strip() # strip leading and trailing spaces
df.columns = df.columns.str.replace(" ", "_") # replace space by _

df.columns

Index(['Protocol', 'Flow_Duration', 'Total_Fwd_Packets',
       'Total_Backward_Packets', 'Total_Length_of_Fwd_Packets',
       'Total_Length_of_Bwd_Packets', 'Fwd_Packet_Length_Max',
       'Fwd_Packet_Length_Min', 'Fwd_Packet_Length_Mean',
       'Fwd_Packet_Length_Std', 'Bwd_Packet_Length_Max',
       'Bwd_Packet_Length_Min', 'Bwd_Packet_Length_Mean',
       'Bwd_Packet_Length_Std', 'Flow_Bytes/s', 'Flow_Packets/s',
       'Flow_IAT_Mean', 'Flow_IAT_Std', 'Flow_IAT_Max', 'Flow_IAT_Min',
       'Fwd_IAT_Total', 'Fwd_IAT_Mean', 'Fwd_IAT_Std', 'Fwd_IAT_Max',
       'Fwd_IAT_Min', 'Bwd_IAT_Total', 'Bwd_IAT_Mean', 'Bwd_IAT_Std',
       'Bwd_IAT_Max', 'Bwd_IAT_Min', 'Fwd_PSH_Flags', 'Bwd_PSH_Flags',
       'Fwd_URG_Flags', 'Bwd_URG_Flags', 'Fwd_Header_Length',
       'Bwd_Header_Length', 'Fwd_Packets/s', 'Bwd_Packets/s',
       'Min_Packet_Length', 'Max_Packet_Length', 'Packet_Length_Mean',
       'Packet_Length_Std', 'Packet_Length_Variance', 'FIN_Flag_Count',
       'SYN_Flag_Count', 'RST_Flag_Count', 'PSH_Flag_Count', 'ACK_Flag_Count',
       'URG_Flag_Count', 'CWE_Flag_Count', 'ECE_Flag_Count', 'Down/Up_Ratio',
       'Average_Packet_Size', 'Avg_Fwd_Segment_Size', 'Avg_Bwd_Segment_Size',
       'Fwd_Avg_Bytes/Bulk', 'Fwd_Avg_Packets/Bulk', 'Fwd_Avg_Bulk_Rate',
       'Bwd_Avg_Bytes/Bulk', 'Bwd_Avg_Packets/Bulk', 'Bwd_Avg_Bulk_Rate',
       'Subflow_Fwd_Packets', 'Subflow_Fwd_Bytes', 'Subflow_Bwd_Packets',
       'Subflow_Bwd_Bytes', 'Init_Win_bytes_forward',
       'Init_Win_bytes_backward', 'act_data_pkt_fwd', 'min_seg_size_forward',
       'Active_Mean', 'Active_Std', 'Active_Max', 'Active_Min', 'Idle_Mean',
       'Idle_Std', 'Idle_Max', 'Idle_Min', 'Inbound', 'Label'],
      dtype='object')

#### Check Missing Values

In [37]:
print("Train dataset")
print(df.isnull().sum())
print("Total Null " , df.isnull().sum().sum())

Train dataset
Protocol                       0
Flow_Duration                  0
Total_Fwd_Packets              0
Total_Backward_Packets         0
Total_Length_of_Fwd_Packets    0
                              ..
Idle_Std                       0
Idle_Max                       0
Idle_Min                       0
Inbound                        0
Label                          0
Length: 79, dtype: int64
Total Null  1620

#### Handle Infinit Values

In [38]:
df.replace([np.inf, -np.inf], np.nan, inplace=True)
print("After replacing infinity:")
print("Total Null", df.isnull().sum().sum())

After replacing infinity:
Total Null 17956

#### Handle Missing Values

In [39]:
# Median is better than mean for skewed network data.
numeric_columns = df.select_dtypes(include=[np.number]).columns

df[numeric_columns] = df[numeric_columns].fillna(df[numeric_columns].median())

In [40]:
print("Total Null Contains row in Train : ", df.isnull().sum().sum())

Total Null Contains row in Train :  0

#### Remove Duplicate Rows

In [ ]:
# print("Before removing duplicates:")
# print("Train : " ,  df.shape , )
# df.drop_duplicates(inplace=True)
# print("After removing duplicates:")
# print("Train : " ,  df.shape)

Before removing duplicates:
Train :  (779478, 79)
After removing duplicates:
Train :  (260302, 79)

In [41]:
df.shape

(346873, 79)

### Feature Selection

#### Remove Constant columns
- Some features always contain the same value.
- These features are useless.

In [42]:
# find constand columns
constant_columns = []

for col in df.columns:
    if df[col].nunique() == 1:
        constant_columns.append(col)

print("Constant Columns: ", constant_columns)
# Constant Columns:  ['Bwd_PSH_Flags', 'Fwd_URG_Flags', 'Bwd_URG_Flags', 'FIN_Flag_Count', 'PSH_Flag_Count', 'ECE_Flag_Count',
#  'Fwd_Avg_Bytes/Bulk', 'Fwd_Avg_Packets/Bulk', 'Fwd_Avg_Bulk_Rate', 'Bwd_Avg_Bytes/Bulk', 'Bwd_Avg_Packets/Bulk', 'Bwd_Avg_Bulk_Rate']

Constant Columns:  ['Bwd_PSH_Flags', 'Fwd_URG_Flags', 'Bwd_URG_Flags', 'FIN_Flag_Count', 'PSH_Flag_Count', 'ECE_Flag_Count', 'Fwd_Avg_Bytes/Bulk', 'Fwd_Avg_Packets/Bulk', 'Fwd_Avg_Bulk_Rate', 'Bwd_Avg_Bytes/Bulk', 'Bwd_Avg_Packets/Bulk', 'Bwd_Avg_Bulk_Rate']

In [43]:
print("Before columns drop : ")
print("Train : " ,  df.shape )
df.drop(columns=constant_columns, inplace=True)
print("After columns drop: ")
print("Train : " ,  df.shape )

Before columns drop :
Train :  (346873, 79)
After columns drop:
Train :  (346873, 67)

#### Remove Irrelevant Feature

- Flow ID, Source IP, Source Port, Destination IP, Destination Port: These features specify who was talking. If we train a model on these, the model will just memorize the IP addresses of the attackers in the CIC dataset rather than learning how the attack looks. It will fail on a new network.
- Timestamp: Decision trees cannot handle raw datetime strings easily, and an attack happens independently of the exact millisecond recorded in 2018.
- SimillarHTTP: Contains highly unstructured text or is mostly missing.
- 'Fwd_Header_Length.1' and 'Fwd_Header_Length' duplicate feature

In [44]:
columns_to_drop = ['Flow_ID', 'Source_IP', 'Source_Port', 'Destination_IP', 'Destination_Port', 'Timestamp', 'SimillarHTTP', 'Fwd_Header_Length.1']

print("Before columns drop : ")
print("Train : " ,  df.shape )
# drop columns if available
df = df.drop(columns=[col for col in columns_to_drop if col in df.columns])
print("After columns drop: ")
print("Train : " ,  df.shape )

Before columns drop :
Train :  (346873, 67)
After columns drop:
Train :  (346873, 67)

### Binary Label generation

In [45]:
all_labels = ['MSSQL', 'NetBIOS', 'SNMP', 'BENIGN', 'NTP', 'UDP', 
              'Portmap', 'DNS', 'LDAP', 'UDPLag', 'SSDP', 'TFTP']

sampled_frames = []

for label in all_labels:
    subset = df[df['Label'] == label]
    
    if label == 'BENIGN':
        sampled_frames.append(subset)
        print(f"Collected all {len(subset)} Benign rows.")
    else:
        n_to_sample = min(10000, len(subset))
        subset_sampled = subset.sample(n=n_to_sample, random_state=42)
        sampled_frames.append(subset_sampled)
        print(f"Sampled {n_to_sample} rows from {label}.")

df_balanced = pd.concat(sampled_frames)

Sampled 10000 rows from MSSQL.
Sampled 10000 rows from NetBIOS.
Sampled 10000 rows from SNMP.
Collected all 30000 Benign rows.
Sampled 10000 rows from NTP.
Sampled 10000 rows from UDP.
Sampled 10000 rows from Portmap.
Sampled 10000 rows from DNS.
Sampled 10000 rows from LDAP.
Sampled 10000 rows from UDPLag.
Sampled 10000 rows from SSDP.
Sampled 10000 rows from TFTP.

In [46]:

df_balanced['Label'] = np.where(df_balanced['Label'] == 'BENIGN', 0, 1)

df_final = df_balanced.sample(frac=1, random_state=42).reset_index(drop=True)

df_final.to_csv('../dataset/binary_modal_dataset.csv', index=False)

print(f"\nFinal dataset saved! Total rows: {df_final.shape[0]}")
print(df_final['Label'].value_counts())

Final dataset saved! Total rows: 140000
Label
1    110000
0     30000
Name: count, dtype: int64

Bengin => 0
Other => 1

### Label Encoding And Feature Scaling

#### Separate Features and Target

In [15]:
X = df.drop(columns=['Label'])
y = df['Label']

#### Encode Target Label

In [16]:
print("Train Lable : ", y.unique())
print("Null : ", y.isnull().sum())

Train Lable :  ['MSSQL' 'NetBIOS' 'SNMP' 'BENIGN' 'NTP' 'UDP' 'Portmap' 'DNS' 'LDAP'
 'UDPLag' 'SSDP' 'TFTP']
Null :  0

#### Label Encoding

In [17]:
#[WARNING ONLY FOR TRAINDATA] Only for Train Data [not for test]
label_encoder = LabelEncoder()
label_encoder.fit(y)
joblib.dump(label_encoder, "../models/LabelEncoder_B.pkl")

['../models/LabelEncoder_B.pkl']

- Binary label

In [46]:
y = pd.Series(label_encoder.transform(y), index=X.index, name='Label')

#### Scale the Features

In [ ]:
# Only For Train data [not for test]
# scaler = RobustScaler()

# scaler.fit(X_train)

RobustScaler()

In [ ]:
# X_train_scaled = scaler.transform(X_train)
# X_test_scaled = scaler.transform(X_test)

In [ ]:
# joblib.dump(scaler, "./models/scaler.pkl")

['./models/scaler.pkl']

In [ ]:
# X_train_scaled = pd.DataFrame(X_train_scaled, columns=X_train.columns, index=X_train.index)
# X_test_scaled = pd.DataFrame(X_test_scaled, columns=X_test.columns, index=X_test.index)

# X_train_scaled.shape, X_test_scaled.shape

((659455, 66), (120199, 66))

#### Recombine Dataset and Save

In [47]:
# df_train = pd.concat([X_train_scaled, y_train], axis=1)
df['Label'] = y
print("Befor : ", df.shape, df.isnull().sum().sum())
df.dropna(inplace=True)
print("After : ", df.shape, df.isnull().sum().sum())

Befor :  (346873, 67) 0
After :  (346873, 67) 0

#### handles outliers

In [63]:
df.replace([np.inf, -np.inf], np.nan, inplace=True)
df.replace([np.inf, -np.inf], np.nan, inplace=True)
X_train = X.clip(-1e6, 1e6)
X_test = X.clip(-1e6, 1e6)
df.isnull().sum().sum()
df.isnull().sum().sum()

np.int64(0)

#### Save Datasete

In [48]:
df.to_csv("../dataset/Clean_CICDDOS_Final_Dataset.csv", index=False)
print("Train datset saved successfully")

Train datset saved successfully